#!/bin/bash
#########################
#  author: Qin Guanri
#  date  : 2016-12-14
#########################

VERSION="1.0.0"

LOG_FILE="/var/log/skylar_backup_restore.log"
# usage: log_info <log_content>
log_info()  { 
    _log "INFO" "$1" 
}

log_warn()  { 
    _log "WARN" "$1" 
}

log_error() { 
    _log "ERROR" "$1" 
}

_log() { 
    echo "$2"; echo "`date` $1 $2" >> $LOG_FILE 
}

#usage: exit_error <error_info>
exit_error() {
    [ "$1" != "" ] && log_error "$1"
    log_error "Failed."
    exit 1
}

exit_ok() {
    log_info "Done."
    exit 0
}

usage() {
    echo "
Scripts used to backup or restore a container's data. version: $VERSION

usage:

sky <command> [options]

the most commonly commands and options are:

list                 
    list all backup files at current container.
            
cleanup [-a|-i index|-f file]           
    clean up backup files at current container. clean up all by default.
    -a          : cleanup all backup files. 
    -i index    : cleanup a backup file specify by index. e.g: -i 2
    -f file     : cleanup a backup file specify by absolut file path. 
                  e.g: -f /backup/container_redis/20161225000000.tar

backup [-f file]            
    create a backup files at current container. 
    -f file     : create a backup file and its absolut path is specify by 'file'.
    default is backup file name by timestamp.

restore [-i index|-f file]     
    restore with a backup file at current container
    -i index    : resotre with a backup file specify by index.
    -f file     : resotre with a backup file specify by file path.
    default is restore by index and index=1.

version|-V|--version
    show the version.

help|-h|--help        
    show this usage.

examples:
1. sky list 
2. sky clean
3. sky backup -f /backup/container_redis/uuid_123.tar
4. sky restore -i 2

At the same time, you can see logfile at $LOG_FILE.

This script is placed in container's directory: /usr/local/bin/.
If you want to execute script outside container, the command would be:
docker exec <container_name> sky <command> [options]
"
    exit 0
}

# which kind of container
CONTAINER_NAME=""
if [ -d "/opt/tools/openresty/nginx" ]; then
    CONTAINER_NAME="main"
elif [ -d "/var/lib/redis" ]; then
    CONTAINER_NAME="redis"
elif [ -d "/var/lib/postgresql" ]; then
    CONTAINER_NAME="pg"
else
    log_error "unexpected container."
    exit 1
fi

# global var
BACKUP_BASE_DIR="/backup/container_$CONTAINER_NAME"
BACKUP_FILE=""
INDEX=""
RESERVE_SIZE=5   # unit GB

#/////////////////////////////////////////////////
# global var for container 'main'
if [ "$CONTAINER_NAME" == "main" ]; then 
    SKYLARMINIDE_DIR="/opt/tools/skylarminide"
fi

#/////////////////////////////////////////////////
# global var for container 'redis'
if [ "$CONTAINER_NAME" == "redis" ]; then
    REDIS_RDB_FILE="/var/lib/redis/dump.rdb"
    REDIS_CONF_FILE="/var/lib/redis/redis.conf"
    REDIS_AOF_FILE="/var/lib/redis/appendonly.aof"
    REDIS_AOF_FILE_OLD="/var/lib/redis/appendonly.aof.old"

    AOF_FILE=""

    REDIS_CLI=`which redis-cli`
fi

#////////////////////////////////////////////////
# global var for container 'postgresql'
if [ "$CONTAINER_NAME" == "pg" ]; then
    INITDB_BIN=`find -P /usr/lib/postgresql/ -name "initdb"`
    PG_CTL_BIN=`find -P /usr/lib/postgresql/ -name "pg_ctl"`
    
    PG_VER=`ls -l /var/lib/postgresql`
    if [ "$PG_VER" == "" ]; then
        log_error "unexpected postgresql version:$PG_VER"
        exit 1
    fi

    PG_DATA_DIR="/var/lib/postgresql/$PG_VER/main"
    PG_DATA_OLD="/var/lib/postgresql/$PG_VER/main_old"

    PG_DUMP_FILE="/var/lib/postgresql/dump.sql"
    PG_CONF=`find -P /var/lib/postgresql -name "postgresql.conf"`
    PG_AUTO_CONF=`find -P /var/lib/postgresql -name "postgresql.auto.conf"`
    PG_IDENT_CONF=`find -P /var/lib/postgresql -name "pg_ident.conf"`
    PG_HBA_CONF=`find -P /var/lib/postgresql -name "pg_hba.conf"`
fi

## check_space $need_size. unit MBytes. 
## return 0 if free space is enough, else return 1.
check_space() {
    log_info "==> check space ..."
    need_size=1
    if [ "$1" -gt 0 ]; then
        need_size=$1
    fi

    total_free_size=`df --block-size=M /backup| tail -1 | awk '{print $4}'`

    let free_size=$total_free_size-$need_size  # MB
    let reserve_size=$RESERVE_SIZE*1024        # MB

    log_info "==> compute space size ..."
    log_info "total_free_size   = $total_free_size MBytes."
    log_info "need_size         = $need_size MBytes."
    log_info "free_size         = $free_size MBytes."
    log_info "reserve_size      = $reserve_size MBytes."

    if [ $free_size -lt $reserve_size ]; then
        log_error "There is not enough reserve space. \
                  Reserve size is $RESERVE_SIZE GB." 
        return 1
    fi

    return 0
}

cmd_list() {
    printf "%5s %10s %20s %20s\n" "index" "size" "createtime" "directory" 
    if [ ! -d $BACKUP_BASE_DIR ]; then
        exit 0
    fi

    cd $BACKUP_BASE_DIR
    ls -lth --time-style="+%Y-%m-%d %H:%M:%S" | sed '1d' | \
    awk '{printf("%5d %10s %9s%9s %s/%s\n", NR, $5, $6, $7, $BACKUP_BASE_DIR, $8)}'
}

# usage: cmd_cleanup [-a|-i index|-f file] 
execute_cleanup() {
    if [ "$BACKUP_BASE_DIR" == "*" ] || 
       [ "$BACKUP_BASE_DIR" == "" ]; then
        log_error "ERROR. Backup directory is invalid. \
                  BACKUP_BASE_DIR=$BACKUP_BASE_DIR"
        return 1
    fi

    log_info "==> clean all backup directories ..."
    rm -rf $BACKUP_BASE_DIR
}

# usage: prepare_backup [-f file]
prepare_backup() {
    log_info "==> begin to backup $CONTAINER_NAME ..."
    if [ $# -eq 0 ]; then
        BACKUP_FILE="$BACKUP_BASE_DIR/`date +%Y%m%d%H%M%S`"
    elif [ $# -eq 2 ] && [ "$1" == "-f" ]; then
        BACKUP_FILE="$2"
    fi

    basename "$BACKUP_FILE" | grep -q '^/backup/[a-zA-Z0-9\.]\+.tar$' >>/dev/null
    if [ $? -ne 0 ]; then
        exit_error "Invalid argumnets. backupfile: $BACKUP_FILE"
    fi

    [ -f $BACKUP_FILE ] && exit_error "Invalid argumnets. $BACKUP_FILE is already exist."

    [ ! -d $BACKUP_BASE_DIR ] && mkdir -p "$BACKUP_BASE_DIR"
}

# usage: cmd_backup [-f file]
execute_backup() {
    case "$CONTAINER_NAME" in
        main)   backup_main;ret_code=$?;;
        redis)  backup_redis;ret_code=$?;;
        pg)     backup_pg;ret_code=$?;;
        *)      exit_error "unexpected container name";exit 1;;
    esac
    if [ $ret_code -ne 0 ]; then
        exit_error "execute backup failed."
    fi
}

backup_main() {
    if [ ! -d "$SKYLARMINIDE_DIR/data" ]; then
        log_error "ERROR. No such file or directory: $SKYLARMINIDE_DIR/data."
        return 1
    fi

    log_info "==> supervisorctl stop skylarminide ..."
    supervisorctl stop skylarminide

    # check space before backup. 
    need_size=`du -s --block-size=M $SKYLARMINIDE_DIR/data | awk {'print $1'}`
    [ ! check_space $need_size ] && return 1
    # check space before backup. 1GB
    [ ! check_space 1024 ] && exit_error

    # BACKUP_FILE="/backup/container_main/xxxxx.tar"
    # SOURCE=/opt/tools/skylarminide/data
    log_info "==> backup data to $BACKUP_FILE ..."
    cd $SKYLARMINIDE_DIR && tar cvf $BACKUP_FILE data

    log_info "==> supervisorctl start skylarminide ..."
    supervisorctl start skylarminide
}

backup_redis() {
    [ ! -f $REDIS_AOF_FILE ] && $REDIS_CLI bgrewriteaof

    if [ ! -f $REDIS_AOF_FILE ]; then
        log_error "ERROR. No such file or directory: $REDIS_AOF_FILE."
        return 1
    fi

    aof_size=`ls -l $REDIS_AOF_FILE | awk '{print $5}'`
    let aof_size＝$aof_size/1024/1024
    [ ! check_space $aof_size ] && exit_error

    cp -f $REDIS_AOF_FILE $BACKUP_BASE_DIR
    cp -f $REDIS_RDB_FILE $BACKUP_BASE_DIR
    cp -f $REDIS_CONF_FILE $BACKUP_BASE_DIR

    cd $BACKUP_BASE_DIR && \
    tar cvf $BACKUP_FILE \
        appendonly.aof \
        dump.rdb \
        redis.conf --remove-files
}

backup_pg() {
    [ ! supervisorctl status postgres ] && supervisorctl start postgres

    # todo:I guess need 2GB space to tar dump.sql here
    data_size=`du -s $PG_DATA_DIR --block-size=M | awk '{print $4}'`
    let dump_size=$data_size/10             # dump.sql is about 1/10 of data directory's size
    [ ! check_space $dump_size ] && exit_error

    log_info "==> pg_dumpall > $PG_DUMP_FILE ..."
    [ ! su postgres -c "pg_dumpall > $PG_DUMP_FILE" ] && return 1

    mv -f $PG_DUMP_FILE $BACKUP_BASE_DIR
    cp -f $PG_CONF $BACKUP_BASE_DIR
    cp -f $PG_HBA_CONF $BACKUP_BASE_DIR
    cp -f $PG_AUTO_CONF $BACKUP_BASE_DIR
    cp -f $PG_IDENT_CONF $BACKUP_BASE_DIR
    cd $BACKUP_BASE_DIR && \
    tar cvf $BACKUP_FILE \
        dump.sql \
        postgresql.conf \
        pg_hba.conf \
        postgresql.auto.conf \
        pg_ident.conf --remove-files

    return 0
}

# prepare_restore [-i index|-f file]

prepare_restore() {
    log_info "==> begin to restore $CONTAINER_NAME ..."

    # step 1. parse arguments.
    if [ $# -eq 0 ]; then
        INDEX=1
    elif [ $# -eq 2 ]; then
        case "$1" in
            -i)  INDEX="$2";;
            -f)  BACKUP_FILE="$2";;
        esac
    fi

    if [ "$INDEX" -gt 0 ]; then
        cd $BACKUP_BASE_DIR
        FILE=`ls -lt | sed '1d' | sed -n "$INDEX p" | awk '{print $9}'`
        BACKUP_FILE="$BACKUP_BASE_DIR/$FILE"
    fi

    # step 2. check files and space
    if [ ! -f "$BACKUP_FILE" ]; then
        exit_error "No such file or directory: $BACKUP_FILE."
    fi

    size=`ls -l $BACKUP_FILE | awk '{print $5}'`
    let size=$size/1024/1024
    [ ! check_space $size ] && exit_error

    # step 3. untar and copy backup file to a temp directory.
    [ -d $BACKUP_BASE_DIR/tmp ] && rm -rf $BACKUP_BASE_DIR/tmp
    mkdir -p $BACKUP_BASE_DIR/tmp

    log_info "==> ready to use $BACKUP_FILE to restore ..." 
    
    cd $BACKUP_BASE_DIR && \
    tar xvf $BACKUP_FILE -C $BACKUP_BASE_DIR/tmp >>/dev/null
    return 0
}

execute_cmd() {
    cmd=$1
    case "$cmd" in
        backup)         "backup_$CONTAINER_NAME";;
        restore)        "restore_$CONTAINER_NAME";;
    esac
    return $?
}

restore_main() {
    SKYLARMINIDE_TMP_DIR="$BACKUP_BASE_DIR/tmp/data"
    if [ ! -d "$SKYLARMINIDE_TMP_DIR" ]; then
        exit_error "No such file or directory: $SKYLARMINIDE_TMP_DIR"
    fi

    if [ ! -d $SKYLARMINIDE_DIR ]; then
        exit_error "ERROR. cannot find $SKYLARMINIDE_DIR."
    fi

    log_info "==> supervisorctl stop skylarminide ..."
    supervisorctl stop skylarminide

    log_info "==> mv $SKYLARMINIDE_DIR/data $SKYLARMINIDE_DIR/data_old ..."
    cp -rf $SKYLARMINIDE_DIR/data $SKYLARMINIDE_DIR/data_old
    rm -rf $SKYLARMINIDE_DIR/data 2>&1 >/dev/null

    log_info "copy $SKYLARMINIDE_TMP_DIR to $SKYLARMINIDE_DIR ..."
    [ ! -d $SKYLARMINIDE_DIR/data ] && mkdir -p $SKYLARMINIDE_DIR/data
    cp -rf SKYLARMINIDE_TMP_DIR/* $SKYLARMINIDE_DIR/data/
    
    log_info "==> supervisorctl start skylarminide ..."
    if ! supervisorctl start skylarminide; then
        log_error "ERROR. supervisorctl start skylarminide failed. rollback ..."

        rm -rf $SKYLARMINIDE_DIR/data
        [ ! -d $SKYLARMINIDE_DIR/data ] && mkdir -p $SKYLARMINIDE_DIR/data
        cp -rf $SKYLARMINIDE_DIR/data_old/* $SKYLARMINIDE_DIR/data/
        rm -rf $SKYLARMINIDE_DIR/data_old
        supervisorctl start skylarminide
        return 1
    fi

    rm -rf $BACKUP_BASE_DIR/tmp
    rm -rf $SKYLARMINIDE_DIR/data_old
    return 0
}

restore_redis() {
    # step 0. check files
    AOF_FILE=`find -P $BACKUP_BASE_DIR/tmp -name "appendonly.aof"`

    if [ ! -f "$AOF_FILE" ]; then
        log_error "No such file or directory:$AOF_FILE."
        rm -rf $BACKUP_BASE_DIR/tmp
        return 1
    fi

    # step 1. stop redis
    log_info "==> supervisorctl stop redis ..."
    supervisorctl stop redis
    [ ps -ef | grep redis-server ] && \
    kill -9 $(ps -ef | grep redis-server | grep 6379 | awk '{print $2}')

    # step 2. restore aof
    log_info "==> $AOF_FILE will be used to restore ..."

    mv $REDIS_AOF_FILE $REDIS_AOF_FILE_OLD
    mv $AOF_FILE $REDIS_AOF_FILE

    # step 3. succeed or rollback.
    log_info "==> supervisorctl start redis ..."
    if ! supervisorctl start redis; then
        log_error "ERROR. supervisorctl start redis failed. rollback ..."
        mv $REDIS_AOF_FILE_OLD $REDIS_AOF_FILE
        supervisorctl restart redis
        rm -rf $BACKUP_BASE_DIR/tmp
        return 1
    fi

    rm -rf $BACKUP_BASE_DIR/tmp
    rm -f $REDIS_AOF_FILE_OLD
    return 0
}

restore_pg() {
    # step 0. check backup files valid
    PG_DUMP_FILE=`find -P $BACKUP_BASE_DIR/tmp -name "dump.sql"`
    PG_CONF_FILE=`find -P $BACKUP_BASE_DIR/tmp -name "postgresql.conf"`
    PG_HBA_CONF=`find -P $BACKUP_BASE_DIR/tmp -name "pg_hba.conf"`
    PG_AUTO_CONF=`find -P $BACKUP_BASE_DIR/tmp -name "postgresql.auto.conf"`
    PG_IDENT_CONF=`find -P $BACKUP_BASE_DIR/tmp -name "pg_ident.conf"`

    if [ ! -f "$PG_DUMP_FILE" ] || [ ! -f "$PG_CONF_FILE" ] || \
       [ ! -f "$PG_HBA_CONF" ]; then
        log_error "No such file or directory:$PG_DUMP_FILE or \
                  $PG_CONF_FILE or $PG_HBA_CONF."
        return 1
    fi

    # step 1. stop pg
    log_info "==> stop pg ..."
    supervisorctl stop postgres >>/dev/null
    [ ps -ef | grep postgres ] && kill -9 $(ps -ef | grep postgres | awk {'print $2'})

    # step 2. backup old data to tmp
    log_info "==> backup $PG_DATA_DIR to $PG_DATA_OLD ..."
    [ -d $PG_DATA_OLD ] && rm -rf $PG_DATA_OLD
    ## cannot move directly. so we copy then remove.
    cp -rf $PG_DATA_DIR $PG_DATA_OLD
    rm -rf $PG_DATA_DIR

    # step 3. create new db
    log_info "==> create new db ..."
    mkdir -p "$PG_DATA_DIR"
    chown -R postgres:postgres $PG_DATA_DIR
    chmod -R 700 $PG_DATA_DIR

    su postgres -c "$INITDB_BIN -D $PG_DATA_DIR"
    sleep 2
    su postgres -c "$PGCTL_BIN -D $PG_DATA_DIR -l logfile stop"
    supervisorctl stop postgres
    [ ps -ef | grep postgres] && \
    kill -9 $(ps -ef | grep postgres | awk {'print $2'})

    ### restore config files
    cp $PG_CONF_FILE $PG_DATA_DIR
    cp $PG_HBA_CONF $PG_DATA_DIR
    cp $PG_IDENT_CONF $PG_DATA_DIR
    cp $PG_AUTO_CONF $PG_DATA_DIR

    # step 4. import dump.sql
    supervisorctl start postgres
    su postgres -c "psql -f $PG_DUMP_FILE 2>&1" >>/dev/null
    rm -rf $BACKUP_BASE_DIR/tmp

    # step 5. succeed or rollback.
    if ! supervisorctl status postgres; then
        log_error "restore failed. rollback ..."
        [ -d $PG_DATA_DIR ] && rm -rf $PG_DATA_DIR
        mv $PG_DATA_OLD $PG_DATA_DIR

        supervisorctl stop postgres
        kill -9 $(ps -ef | grep postgres | awk {'print $2'})
        supervisorctl start postgres
        return 1
    fi

    rm -rf $PG_DATA_OLD
}

# do some common works after restoring
summary_restore() {
    [ -d "$BACKUP_BASE_DIR/tmp" ] && rm -rf $BACKUP_BASE_DIR/tmp
}

cmd_list() {
    execute_list $@
}

cmd_cleanup() {
    execute_cleanup $@
}

cmd_backup() {
    prepare_backup $@
    execute_backup
    summary_backup
}

cmd_restore() {
    prepare_restore $@
    execute_restore
    summary_restore
}

# What kind of command ？
case "$1" in
    list)           cmd_list $@;;
    cleanup)        cmd_cleanup $@;;
    backup)         cmd_backup $@;;
    restore)        cmd_restore $@;;   
    version|-V|--version)    echo "version: $VERSION";;
    help|usage|-h|--help)    usage;;
    *)                       usage;;
esac

if [ $? -eq 0 ]; then
    exit_ok
else
    exit_error
fi