#!/bin/bash
#########################
#  author: Qin Guanri
#  date  : 2016-12-14
#########################

VERSION="1.0.0"
BACKUP_BASE_DIR="/backup/container_main"
DIRRECTORY=""                       # the relative directory path of backup files. 
INDEX=""

BACKUP_FILE=""

usage() {
    echo "
usage:

docker exec main clean [options]

the most commonly options are:
-i  index       clean a backup directory by index. 
                default is by index, the default index is the max index number. e.g: -i 2

-d  directory   clean a backup directory. e.g: -d a1b2c3d4e5

-a              clean all backup directories.

-h              show this usage.     

example:
docker exec main clean
"
    exit 0
}

## skylar_log <level> <content>
skylar_log() {
    echo "$2"
    echo  "`date` $1 $2" >> /var/log/skylar_backup_restore.log
}

clean_all() {
    if [ "$BACKUP_BASE_DIR" == "*" ] || [ "$BACKUP_BASE_DIR" == "" ]; then
        skylar_log "ERROR" "ERROR. Backup directory is invalid. BACKUP_BASE_DIR=$BACKUP_BASE_DIR"
        return 1
    fi

    skylar_log "INFO" "==> clean all backup directories ..."
    rm -rf $BACKUP_BASE_DIR
}

main() {
    clean_all

    if [ $? -eq 0 ]; then
        echo "Done."
        exit 0
    else
        echo "Failed."
        exit 1
    fi
}


args=`getopt "i:d:ahV" $*`
if [ $? -ne 0 ]
then
    usage
fi

set -- $args
for i in $*
do
    case "$i" in
    -i) INDEX=$2; shift 2;echo "has not support this commond yet.";exit 0;;
    -d) DIRRECTORY=$2; shift 2;echo "has not support this commond yet.";exit 0;;
    -a) clean_all;exit $?;;
    -h) usage;;
    -V) echo "version $VERSION"; exit 0;;
    -\?) usage;;
    --) shift; break;;
    esac
done

#### main
main
